version: '3'
services:
  db:
    image: postgres
    container_name: db
    restart: always
    ports:
    - 5432:5432
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=secret
    - POSTGRES_DB=task_db
    volumes:
    - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql
    - ./postgres-data:/var/lib/postgresql/data
    networks:
    - app-network

  api:
    image: nickbarak/tasker-api
    container_name: api
    depends_on:
    - db
    ports:
    - 8081:8081
    environment:
    - PORT=8081
    - DB_USER=postgres
    - DB_PASSWORD=secret
    - DB_HOST=db
    - DB_PORT=5432
    - DB_NAME=tasks_db
    - CLIENT_HOST=ui
    - CLIENT_PORT=3000
    networks:
    - app-network

  ui:
    image: nickbarak/tasker-ui
    container_name: ui
    depends_on:
    - api
    ports:
    - 80:3000
    environment:
    - REACT_APP_API_HOST=api
    - REACT_APP_API_PORT=8081
    networks:
    - app-network

networks:
  app-network:
    external: false